jwt:
  secret: ""

database:
  url: postgres://user:password@host:port/database

redis:
  host: ""
  port: 0
  password: ""

github:
  app_id: 0
  private_key: -----BEGIN RSA PRIVATE KEY-----\n[...]\n-----END RSA PRIVATE KEY-----

  client_id: ""
  client_secret: ""

  installation_id: 0

expo:
  access_token: ""
